version: '3'
services:
    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./frontend/dist:/public
        restart: always

    slidecloud:
        build: ./app
        environment:
            SC_APP_PORT   : '5000'
            SC_DB_HOST    : 'mysql'
            SC_DB_PORT    : '3306'
            SC_DB_USER    : 'root'
            SC_DB_PASSWORD: 'root'
            SC_DB_NAME    : 'slidecloud'
        command:
            - "sh"
            - "-c"
            - "dep ensure && go run ./main.go"
        working_dir: /go/src/app
        volumes:
            - ./app/src/app:/go/src/app
        restart: always

    mysql:
        image: mysql:8.0
        environment:
            TZ                 : 'Asia/Tokyo'
            MYSQL_ROOT_PASSWORD: 'root'
        volumes:
            - mysql:/var/lib/mysql
            - ./mysql:/etc/mysql/conf.d
            - ./sql:/docker-entrypoint-initdb.d
        # development only
        ports:
          - "13306:3306"
        restart: always

volumes:
    mysql:
