export const CHANGE_VIEW_MODE = 'CHANGE_VIEW_MODE';
export const TOGGLE_VIEW_MODE = 'TOGGLE_VIEW_MODE';
export const CHANGE_EDITOR_CONTENT = 'CHANGE_EDITOR_CONTENT';
export const CHANGE_SLIDE_NUMBER = 'CHANGE_SLIDE_NUMBER';
