use slidecloud;

CREATE TABLE IF NOT EXISTS user (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL,
    password VARBINARY(191) NOT NULL,
    created_at DATETIME NOT NULL,
    deleted BOOLEAN DEFAULT 0 NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY (name)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE IF NOT EXISTS slide (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    access_token VARCHAR(16) NOT NULL,
    public BOOLEAN DEFAULT 0 NOT NULL,
    name VARCHAR(128) NOT NULL,
    content LONGTEXT NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted BOOLEAN DEFAULT 0 NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY (access_token)
    -- UNIQUE KEY (user_id, name)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE IF NOT EXISTS history (
    id BIGINT NOT NULL AUTO_INCREMENT,
    slide_id BIGINT NOT NULL,
    message VARCHAR(1024) NOT NULL,
    content LONGTEXT NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted BOOLEAN DEFAULT 0 NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE IF NOT EXISTS image (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    access_token BINARY(16) NOT NULL,
    content LONGBLOB NOT NULL,
    created_at DATETIME NOT NULL,
    deleted BOOLEAN DEFAULT 0 NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY (access_token)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4;
